import Head from 'next/head'

import React, {useState, useEffect} from 'react'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [state, setState] = useState<ProductType[]>([])

  useEffect(() => {
    const getProducts = async () => {
      const response = await fetch('http://localhost:3000/api/products')
      const data = await response.json()
      setState(data)
    }

    getProducts()
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ul>
        {state.map(({id, product, description, price, product_image}) => (
          <Link href={`/products/${id}`}>
            <a>
              <li key={id}>{product}</li>
            </a>
          </Link>
        ))}
      </ul>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
